<?php

/**
 * @file
 * twig svg functions.
 */

/**
 * Implements hook_preprocess_html().
 */
function twig_svg_preprocess_html(&$variables) {
  $admin_context = \Drupal::service('router.admin_context');

  // Avoid admin pages.
  if (!$admin_context->isAdminRoute()) {
    // Get the contents of the SVG sprite.
    // TODO need to cater for icons not in this folder....
    $icons = file_get_contents(\Drupal::theme()->getActiveTheme()->getPath() . '/images/icons.svg');

    $variables['page_bottom']['icons'] = [
      '#type' => 'inline_template',
      '#template' => '<span class="hidden">' . $icons . '</span>',
    ];
  }
}
