<?php

/**
 * @file
 * twig_svg functions.
 */

/**
 * Implements hook_preprocess_html().
 */
function twig_svg_preprocess_html(&$variables) {
  $admin_context = \Drupal::service('router.admin_context');

  // Avoid admin pages.
  if (!$admin_context->isAdminRoute()) {
    $icon_path = \Drupal::theme()->getActiveTheme()->getPath() . '/images/icons.svg';

    if (file_exists($icon_path)) {
      // Get the contents of the SVG sprite.
      $icons = file_get_contents($icon_path);

      $variables['page_bottom']['icons'] = [
        '#type' => 'inline_template',
        '#template' => '<span class="hidden">' . $icons . '</span>',
      ];
    }
  }
}
